### ISSUE TITLE
API call to testconsole fails

### ISSUE THREAD

**Issue by pserdiuk-everstake** [kandola-network/data3-testnet-docker#1]
node-provider-1 container log file is attached
[LogFile.log](https://github.com/kandola-network/data3-testnet-docker/files/14424106/LogFile.log)

docker-compose of node-provider:
```
#version: '2.24.5'
version: '3'
services:
  provider-db:
    container_name: provider-db-1
    image: mongo:latest
    volumes:
      - provider-db-volume:/data/db
    expose:
      - 27017
    ports:
      - 27018:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    networks:
      - provider-network
  provider-app:
    container_name: provider-app-1
    image: kandolanetwork/data3-node-provider:latest
    environment:
      GRAILS_ENV: development
      DB_HOST: provider-db
      DB_PORT: 27017
      DB_DATABASE: KandolaNodeProvider
      BOOTSTRAP_BASE_URL: https://testconsoleapi.data3.network/
      BOOTSTRAP_PUBSUB_HOST: testpubsub.data3.network
      BOOTSTRAP_PUBSUB_PORT: 9092
      P2P_PORT: 29092

      NODE_IP: 157.90.181.45
      NODE_HOST_NAME: 157.90.181.45
      SELF_PUBSUB_HOST: 157.90.181.45
      SELF_PUBSUB_PORT: 29092

      API_KEY: o3h4iIZoaZM8Z7QjawQFKSr8obe3IN8GxjxuXQDhkSMyDFLfkkEJI3Mvt65LVQQF
      API_SECRET: dWSGC4rWl6STLJUs9niRqloPs8f3WvLI
      ADDRESS: 0x09f6C435980767bfEF7F8cC364018D8605C5554c
      PRIVATE_KEY: dc9f27163486295eec097b6e10fee504f650db64a2ea82028f81a505bc670a7b

      EXTERNAL_API_ENDPOINT: https://host.docker.internal:3080/price
    volumes:
      - provider-app-volume:/app/data_home
    expose:
      - 8080
    ports:
      - 8081:8080
    depends_on:
      provider-db:
        condition: service_healthy
    links:
      - provider-db
    networks:
      - provider-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  provider-app-volume:
  provider-db-volume:
networks:
  provider-network:
    driver: bridge
```
docker-compose of all-deps:
```
version: '3'
services:
  zookeepern:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    expose:
      - 2181
    ports:
      - 22181:2181
    networks:
      - npdepsnet
    volumes:
      - zookeepern-volume:/bitnami/zookeeper
  kafkan:
    image: bitnami/kafka:latest
    depends_on:
      - zookeepern
    links:
      - zookeepern
    expose:
      - 29092
    ports:
      - 29092:9092
    environment:
      - KAFKA_BROKER_ID= 1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://157.90.181.45:29092
      - KAFKA_ZOOKEEPER_CONNECT=zookeepern:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - npdepsnet
    volumes:
      - kafkan-volume:/bitnami/kafka
    extra_hosts:
      - "host.docker.internal:host-gateway"
  observability-server:
    image: percona/pmm-server:2
    restart: always
    expose:
      - 443
    ports:
      - 8443:443
    volumes:
      - pmm-server-volume:/srv
    networks:
      - npdepsnet
volumes:
  zookeepern-volume:
  kafkan-volume:
  pmm-server-volume:
networks:
  npdepsnet:
    driver: bridge
```
Curl to the same endpoint was successful from inside the node-provider-1 container.
